import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = ['main.c','map.c']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
